name: Publish Package

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  Contentstack_Api_Key: ${{ vars.CONTENTSTACK_API_KEY }}
  Contentstack_Branch: ${{ vars.CONTENTSTACK_BRANCH }}
  Contentstack_Management_API: ${{ vars.CONTENTSTACK_MANAGEMENT_API }}
  Contentstack_Management_Token: ${{ secrets.CONTENTSTACK_MANAGEMENT_TOKEN }}
  Beacon_Extension: ${{ vars.BEACON_EXTENSION }}
  Beacon_Plugin: ${{ vars.BEACON_PLUGIN }}

jobs:
  publish-package:
    runs-on: ubuntu-latest
    environment: dev
    concurrency: dev-stack

    permissions:
      contents: read
      id-token: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare dependencies
        uses: ./.github/actions/prepare-dependencies

      - name: Publish CLI package to NPM
        shell: bash
        run: yarn workspace @arkebcacy/qorvo-beacon-cli npm publish --access public
        env:
          YARN_NPM_PUBLISH_REGISTRY: https://registry.npmjs.org
          YARN_NPM_AUTH_TOKEN: ${{ secrets.PUBLISH_PACKAGES_NPM }}

      - name: Publish CLI package to GitHub
        shell: bash
        run: yarn workspace @arkebcacy/qorvo-beacon-cli npm publish
        env:
          YARN_NPM_PUBLISH_REGISTRY: https://npm.pkg.github.com
          YARN_NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
